[package]
name = "vw-proto"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[lib]
test = false

[dependencies]
prost = "=0.14.4"
serde = { version = "=1.0.229", features = ["derive"] }

[build-dependencies]
prost-build = "=0.14.4"
protoc-bin-vendored = "=3.2.0"
